FROM python:3.11-slim

WORKDIR /app

# Copiar requirements e instalar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY . .

# Exponer puerto
ENV HOST=0.0.0.0
ENV PORT=8000
# Para MQTT_BROKER, se inyecta desde Compose

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
